<?php
/**
 * @file
 * Code for the Kalamuna Picture Pane for responsive images across multiple pages
 */

include_once 'hot_primary_tout.features.inc';

/**
 * Implementation of hook_entity_info_alter()
 */
function hot_primary_tout_entity_info_alter(&$entity_info) {
  // Fieldable panel pane bundle to support call-to-action
  $entity_info['fieldable_panels_pane']['bundles']['hot_primary_tout_quarter'] = array(
    'label' => t('Add 1/3 width responsive image, 3 columns'),
    'pane category' => t('Custom'),
    'pane top level' => TRUE,
    'pane icon' => drupal_get_path('module', 'panopoly_widgets') . '/images/icon_image.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      'real path' => 'admin/structure/fieldable-panels-panes/manage/hot_primary_tout_quarter',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}


/**
 * Implements hook_system_info_alter().
 */


/**
 * Implements hook_preprocess_panels_pane().
 */
function hot_primary_tout_preprocess_panels_pane(&$variables){
  if(isset($variables['content']['#bundle'])){
    $bundle = $variables['content']['#bundle'];
    if(strpos($bundle, 'hot_primary_tout') === 0){

      $variables['theme_hook_suggestions'][] = 'fieldable_panels_panes__hot_primary_tout';
      
    }

  }
}

/**
 * Implements hook_theme_registry_alter().
 */
function hot_primary_tout_theme_registry_alter(&$theme_registry) {
  $theme_registry['fieldable_panels_panes__hot_primary_tout'] = array(
    'template' => drupal_get_path('module', 'hot_primary_tout') . '/templates/fieldable-panels-panes--hot-primary-tout',
    'theme path' => drupal_get_path('module', 'hot_primary_tout'),
    'type' => 'module',
  );
}
